config/routes.rb
RoomService::Application.routes.draw do

  get 'main', controller: :hotels, action: :main
    resources :hotels, only: [:main, :index, :show] do
    resources :coments, only: [:new, :create]
    resources :photos
  end

  devise_for :users

  match '/rate' => 'rater#create', :as => 'rate'

  resources :users, except: [:destroy, :index] do
    resources :hotels do 
      get '/visited' => 'hotels#add_to_visited', :as => :visited
    end
  end

  root :to => 'hotels#main'

end

app/models/coment.rb
class Coment < ActiveRecord::Base
  belongs_to :hotel
  attr_accessible :mark
  belongs_to :user
   attr_accessible :hotel_id
end

app/controllers/coments_controller.rb
class ComentsController < ApplicationController

  def new
    @hotel = Hotel.find(params[:hotel_id])
    @coment = @hotel.coments.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @coment }
    end
  end
  
  def create
    @hotel = Hotel.find(params[:hotel_id])
    @coment = @hotel.coments.build(params[:coment])
    @coment.user = current_user
    respond_to do |format|
      if @coment.save
        format.html { redirect_to hotel_path(@hotel)}
        format.json { render :json => @coment, :status => :created, :location => [@coment.hotel, @coment] }
      else
        format.html { render :action => "new" }
        format.json { render :json => @coment.errors, :status => :unprocessable_entity }
      end
    end
  end
end

app/helpers/coments_helper.rb
module ComentsHelper
end

app/views/coments/_form.html.erb
<%= form_for([@coment.hotel, @coment]) do |f| %>
  <% if @coment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@coment.errors.count, "error") %> prohibited this coment from being saved:</h2>

      <ul>
      <% @coment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mark %><br />
    <%= f.text_area :mark %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/coments/edit.html.erb
<h1>Editing coment</h1>

<%= render 'form' %>

<%= link_to 'Show', [@coment.hotel, @coment] %> |
<%= link_to 'Back', hotel_coments_path(@coment.hotel) %>

app/views/coments/index.html.erb
<h1>Listing coments</h1>

<table>
  <tr>
    <th>Mark</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @coments.each do |coment| %>
  <tr>
    <td><%= coment.mark %></td>
    <td><%= coment.user.name %></td>
    <td><%= link_to 'Show', [coment.hotel, coment] %></td>
    <td><%= link_to 'Edit', edit_hotel_coment_path(coment.hotel, coment) %></td>
    <td><%= link_to 'Destroy', [coment.hotel, coment], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Coment', new_hotel_coment_path(params[:hotel_id]) %>

app/views/coments/new.html.erb
<h1>New coment</h1>

<%= render 'form' %>

<%= link_to 'Back', hotel_coments_path(@coment.hotel) %>

app/views/coments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Mark:</b>
  <%= @coment.mark %>
</p>


<%= link_to 'Edit', edit_hotel_coment_path(@coment.hotel, @coment) %> |
<%= link_to 'Back', hotel_coments_path(@coment.hotel) %>