config/routes.rb
RoomService::Application.routes.draw do

  get 'main', controller: :hotels, action: :main
    resources :hotels, only: [:main, :index, :show] do
    resources :coments, only: [:new, :create]
    resources :photos
  end

  devise_for :users

  match '/rate' => 'rater#create', :as => 'rate'

  resources :users, except: [:destroy, :index] do
    resources :hotels do 
      get '/visited' => 'hotels#add_to_visited', :as => :visited
    end
  end

  root :to => 'hotels#main'

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  #validates_format_of :image, with: /$[jpg|bmp|png]/, message: "Invalid format must be (jpg, bmp, png)"

  attr_accessible :title, :image, :remote_image_url, :hotel_id
  belongs_to :hotel
  mount_uploader :image, ImageUploader
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # GET hotels/1/photos
  # GET hotels/1/photos.json
  def index
    @hotel = Hotel.find(params[:hotel_id])
    @photos = @hotel.photos

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @photos }
    end
  end

  # GET hotels/1/photos/1
  # GET hotels/1/photos/1.json
  def show
    @hotel = Hotel.find(params[:hotel_id])
    @photo = @hotel.photos.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @photo }
    end
  end

  # GET hotels/1/photos/new
  # GET hotels/1/photos/new.json
  def new
    @hotel = Hotel.find(params[:hotel_id])
    @photo = @hotel.photos.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @photo }
    end
  end

  # GET hotels/1/photos/1/edit
  def edit
    @hotel = Hotel.find(params[:hotel_id])
    @photo = @hotel.photos.find(params[:id])
  end

  # POST hotels/1/photos
  # POST hotels/1/photos.json
  def create
    @hotel = Hotel.find(params[:hotel_id])
    @photo = @hotel.photos.build(params[:photo])

    respond_to do |format|
      if @photo.save
        format.html { redirect_to([@photo.hotel, @photo], :notice => 'Photo was successfully created.') }
        format.json { render :json => @photo, :status => :created, :location => [@photo.hotel, @photo] }
      else
        format.html { render :action => "new" }
        format.json { render :json => @photo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT hotels/1/photos/1
  # PUT hotels/1/photos/1.json
  def update
    @hotel = Hotel.find(params[:hotel_id])
    @photo = @hotel.photos.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to([@photo.hotel, @photo], :notice => 'Photo was successfully updated.') }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @photo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE hotels/1/photos/1
  # DELETE hotels/1/photos/1.json
  def destroy
    @hotel = Hotel.find(params[:hotel_id])
    @photo = @hotel.photos.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to hotel_photos_url(hotel) }
      format.json { head :ok }
    end
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_for([@photo.hotel, @photo], :html => {:multipart => true} ) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :remote_image_url, "or Photo url" %><br />
    <%= f.text_field :remote_image_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', [@photo.hotel, @photo], class: "btn btn-primary" %> 
<%= link_to 'Back', hotel_photos_path(@photo.hotel), class: "btn btn-success" %>

app/views/photos/index.html.erb
<h1>Listing photos</h1>

<table>
  <tr>
   
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @photos.each do |photo| %>
  <tr>
    <td>
      <%= image_tag photo.image_url.to_s , size: "100x100"%>
    </td>
    <td>
      <%= link_to 'Show', [photo.hotel, photo], class: "btn btn-primary" %>
    </td>
      <% if current_user.hotels.include?(@hotel)%>
    <td>
      <%= link_to 'Edit', edit_hotel_photo_path(photo.hotel, photo), class: "btn btn-success" %>
    </td>
    <td>
      <%= link_to 'Destroy', [photo.hotel, photo], :confirm => 'Are you sure?', :method => :delete ,class: "btn btn-danger"%>
    </td>
  </tr>
      <%end%>
<% end %>
</table>

<br />

<%= link_to 'New Photo', new_hotel_photo_path(params[:hotel_id]), class:"btn btn-primary" %>
<br />
<br />
<%= link_to "Back", hotel_path(@hotel), class: "btn btn-primary"%>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

<%= link_to 'Back', hotel_photos_path(@photo.hotel) %>

app/views/photos/show.html.erb
<h3 align="center"><%= "#{@hotel.title} Photos"%></h3>


<p>
  <b>Title:</b>
  <%= @photo.title %>
</p>
<div>
<%= image_tag @photo.image_url.to_s , size: "500x500"%></div>
<br />
<%= link_to 'Edit', edit_hotel_photo_path(@photo.hotel, @photo), class: "btn btn-success" %> 
<%= link_to 'Back', hotel_photos_path(@photo.hotel), class: "btn btn-primary" %>