config/routes.rb
RoomService::Application.routes.draw do

  get 'main', controller: :hotels, action: :main
    resources :hotels, only: [:main, :index, :show] do
    resources :coments, only: [:new, :create]
    resources :photos
  end

  devise_for :users

  match '/rate' => 'rater#create', :as => 'rate'

  resources :users, except: [:destroy, :index] do
    resources :hotels do 
      get '/visited' => 'hotels#add_to_visited', :as => :visited
    end
  end

  root :to => 'hotels#main'

end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
  validates :price, :format => { :with => /^\d+??(?:\.\d{0,2})?$/ }, :numericality => {:greater_than => 0}
  validates_presence_of  :price, :room_description, :title,
                        :country, :state, :city, :street


  has_many :photos
  has_many :coments
  belongs_to :user
  
  attr_accessible :address, :breakfast, :price, :room_description, :title, :hotel_id, :user_id, 
  				  :country, :state, :city, :street, :get_addres
  attr_accessor :country, :state, :city, :street

before_save :coupling
after_find :get_address



	def self.get_top_five_hotels
		top_ratings = RatingCache.find(:all, :order => "avg DESC", :limit => 5)
		Hotel.find(top_ratings.map{|hotel| hotel.cacheable_id})
	end
	
protected
	def get_address
		self.country, self.state, self.city, self.street = self.address.split '/'
		return self
	end

	def coupling
		self.address = [country, state, city, street].join('/')
	end
   letsrate_rateable "mark"
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  # GET users/1/hotels
  # GET users/1/hotels.json
  #require 'will_paginate/array'

  def index
  if params[:user_id]
    @user = User.find(params[:user_id])
    visited = @user.visited
    @hotels = Hotel.find(visited).paginate(:page =>params[:page], :per_page => 5)
    page = "visited_hotels"
  else
    @hotels = Hotel.all.paginate(:page =>params[:page], :per_page => 5)
  end

    respond_to do |format|
      format.html {render page}
      format.json { render :json => @hotels }
    end
  end

  # GET users/1/hotels/1
  # GET users/1/hotels/1.json
  def show
    @hotel = Hotel.find(params[:id])
    @coments = @hotel.coments.order('created_at DESC').paginate(:page =>params[:page], :per_page => 5)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @hotel }
    end
  end

  # GET users/1/hotels/new
  # GET users/1/hotels/new.json
  def new
    @user = User.find(params[:user_id])
    @hotel = @user.hotels.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @hotel }
    end
  end

  # GET users/1/hotels/1/edit
  def edit
    @user = User.find(params[:user_id])
    @hotel = @user.hotels.find(params[:id])
  end

  # POST users/1/hotels
  # POST users/1/hotels.json
  def create
    @user = User.find(params[:user_id])
    @hotel = @user.hotels.build(params[:hotel])
    respond_to do |format|
      if @hotel.save
        format.html { redirect_to(user_hotel_visited_path(current_user, @hotel), :notice => 'Hotel was successfully created.') }
        format.json { render :json => @hotel, :status => :created, :location => [@hotel.user, @hotel] }
      else
        format.html { render :action => "new" }
        format.json { render :json => @hotel.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT users/1/hotels/1
  # PUT users/1/hotels/1.json
  def update
    @user = User.find(params[:user_id])
    @hotel = @user.hotels.find(params[:id])

    respond_to do |format|
      if @hotel.update_attributes(params[:hotel])
        format.html { redirect_to([@hotel.user, @hotel], :notice => 'Hotel was successfully updated.') }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @hotel.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE users/1/hotels/1
  # DELETE users/1/hotels/1.json
  def add_to_visited
    @user = User.find(params[:user_id])
    visited = @user.visited_hotels     
    @user.visited_hotels = [visited, params[:hotel_id]].join(' ')
    @user.save
    redirect_to user_hotels_path(@user)
  end

  def main
    @top_hotels = Hotel.get_top_five_hotels
  end

end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/hotels/_form.html.erb
<%= form_for([@hotel.user, @hotel]) do |f| %>
  <% if @hotel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>

      <ul>
      <% @hotel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :breakfast %>
    <%= f.check_box :breakfast %>
  </div>

  <div class="field">
    <%= f.label :price_for_room_in_USD %>
    <%= f.text_field :price %>
  </div>

<div class="address">
  <h4>Address<h4>
  <div class="field">
    <%= f.label :country %>
    <%= f.text_field :country %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

    <div class="field">
    <%= f.label :street %>
    <%= f.text_field :street %>
  </div>
    <div class="field">
    <%= f.label :room_description %>
    <%= f.text_area :room_description, :rows => 7, :class => "span7" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary"%>
  </div>
</div>
<% end %>

app/views/hotels/edit.html.erb
<h1>Editing hotel</h1>

<%= render 'form' %>

<%= link_to 'Show', [@hotel.user, @hotel] %> |
<%= link_to 'Back', user_hotels_path(@hotel.user) %>

app/views/hotels/index.html.erb
<h1>Listing hotels</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Breakfast</th>
    <th>Room description</th>
    <th>Price</th>
    <th>Address</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @hotels.each do |hotel| %>
  <tr>
    <td><%= hotel.title %></td>
    <td><%= hotel.breakfast %></td>
    <td><%= hotel.room_description %></td>
    <td><%= hotel.price %></td>
    <td><%= hotel.address %></td>
        <%if !current_user.visited.include?(hotel.id.to_s)%>
    <td><%= link_to 'Add to viseted', user_hotel_visited_path(current_user, hotel) %></td>
    <%end%>
    <td><%= link_to 'Show', hotel %></td>
  
    
<% end %>
</table>

<br />
<%= link_to 'New Hotel', new_user_hotel_path(current_user) %>

app/views/hotels/main.html.erb
<h1>Welcome To Room Service</h1>



<table class="table table-striped table-hover">
  <tr>
    <th >Hotel</th>
    <th>Address</th>
    <th>Show</th>
    <th>Add</th>
    
  </tr>

<% @top_hotels.each do |hotel| %>
  <tr>
    <td><%= hotel.title %></td>
    <td>
        <ul>
            <li>
                <b>Country: </b>
                <%= hotel.country %>
            </li>
            <li>
                <b>State: </b>
                <%= hotel.state %>
            </li>
            <li>
                <b>City: </b>
                <%= hotel.city %>
            </li>
            <li>
                <b>Street: </b>
                <%= hotel.street %>
            </li>                                    
        </ul>
    </td>
    <td><%= link_to 'Show', hotel, class: "btn btn-primary"%></td>
    <td ><%if !current_user.visited.include?(hotel.id.to_s)%>
    <%= link_to ' Add to viseted', user_hotel_visited_path(current_user, hotel), class: "icon-plus btn btn-primary"%>
    <%else%>
    <h4>Visited</h4>
    <%end%>
    </td>
  

    
<% end %>
</table>



<br />
<%= link_to 'New Hotel', new_user_hotel_path(current_user), class: "btn btn-primary" %>

app/views/hotels/new.html.erb
<h1>New hotel</h1>

<%= render 'form' %>

<%= link_to 'Back', user_hotels_path(@hotel.user), class: "btn" %>

app/views/hotels/show.html.erb
<h2 align="center">
  <%= @hotel.title %>
</h2>

<div align="center">
 <%= rating_for @hotel, "mark", class:"rating" %>
</div>

<%= link_to "Photos", hotel_photos_path(@hotel), class: "btn btn-primary"%>
<p id="notice"><%= notice %></p>


<p>
  <b>Room description:</b><br />
  <%= @hotel.room_description %>
</p>
    <button type="button" class="btn btn-danger" data-toggle="collapse" data-target="#demo">
    Details
    </button>
     
    <div id="demo" class="collapse out">
      <br />
<div id="details">
<br />
<p>
  <b>Breakfast:</b>
  <%= @hotel.breakfast %>
</p>

<p>
  <b>Price for room:</b>
  <%= @hotel.price %>
</p>


  <h4>Address</h4>
<p>
  <b>Country:</b>
  <%= @hotel.country %>
</p>

<p>
  <b>State:</b>
  <%= @hotel.state %>
</p>

<p>
  <b>City:</b>
  <%= @hotel.city %>
</p>

<p>
  <b>Street:</b>
  <%= @hotel.street %>
</p>
<br />
</div>
    </div>

<%= form_for([@hotel, Coment.new]) do |f| %>
  

  <div class="field">
    <%= f.label :Coment %>
    <%= f.text_area :mark, :rows => 7, :class => "span7"%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<table class="table table-striped table-hover">
  <tr>
    <th>Author</th>
    <th>Mark</th>

  </tr>

<% @coments.each do |coment| %>
  <tr>
    <td>
      <%= link_to "#{coment.user.name}", user_hotels_path(coment.user), class: "btn btn-primary"%>
    </td>
    
    <td><%= coment.mark %></td>
    
    
  </tr>
<% end %>
</table>

<div id="pagination">
  <%= will_paginate @coments %>
</div>

app/views/hotels/visited_hotels.html.erb
<h1>Visited Hotels</h1>

<table class="table table-striped table-hover">
  <tr>
    <th >Hotel</th>
    <th>Address</th>
    <th>Show</th>
    
  </tr>

<% @hotels.each do |hotel| %>
  <tr>
    <td><%= hotel.title %></td>
    <td>
        <ul>
            <li>
                <b>Country: </b>
                <%= hotel.country %>
            </li>
            <li>
                <b>State: </b>
                <%= hotel.state %>
            </li>
            <li>
                <b>City: </b>
                <%= hotel.city %>
            </li>
            <li>
                <b>Street: </b>
                <%= hotel.street %>
            </li>                                    
        </ul>
    </td>
    <td><%= link_to 'Show', hotel, class: "btn btn-primary" %></td>

    </td>
  

    
<% end %>
</table>
<div id="pagination">
<%= will_paginate @hotels %>
</div>
<br />
<%= link_to 'New Hotel', new_user_hotel_path(current_user), class: "btn btn-primary" %>